//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.23 at 12:12:52 AM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.springframework.org/schema/web-services", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.eif.viko.m.danys.producingwebservice.generated_classes;
